Repository googleapis/gcp-metadata, pull requests merged in 2020-09, with the labels that each got.

#408 test: update dependencies in kitchen sink test
  system-test/fixtures/kitchen/package.json
Labels: cla: yes

#409 build(test): recursively find test files; fail on unsupported dependency versions
  .github/workflows/ci.yaml
  .mocharc.js
  synth.metadata
Labels: automerge, cla: yes, context: full

#406 feat: add support for GCE_METADATA_HOST environment variable
  README.md
  gcp-metadata-4.1.4.tgz
  src/index.ts
  synth.metadata
  test/index.test.ts
Labels: cla: yes

#411 chore: start tracking obsolete files
  synth.metadata
Labels: cla: yes, context: full
