Repository googleapis/gcp-metadata, pull requests merged in 2020-07, with the labels that each got.

#370 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#371 fix: typeo in nodejs .gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#366 docs: add ProjectID and nested properties examples
  README.md
Labels: cla: yes

#381 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#387 build: fix typo in publish
  .kokoro/publish.sh
  synth.metadata
Labels: automerge, cla: yes, context: partial

#388 chore: add config files for cloud-rad for node.js
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: cla: yes, context: full

#390 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#391 build: rename _toc to toc
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#392 build: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: cla: yes, context: full

#395 chore(node): fix kokoro build path for cloud-rad
  .kokoro/release/docs-devsite.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full
