Repository googleapis/gcp-metadata, pull requests merged in 2025-02, with the labels that each got.

#604 refactor: `fastFailMetadataRequest` to use `Promise.any`
  src/index.ts
  test/index.test.ts
  tsconfig.json
Labels: size: m

#650 chore: Fix and Update System Tests for Node 18
  system-test/fixtures/cloudbuild/cloudbuild.yaml
  system-test/fixtures/cloudbuild/package.json
  system-test/fixtures/hook/package.json
  system-test/fixtures/kitchen/package.json
  system-test/fixtures/kitchen/src/index.ts
  system-test/fixtures/kitchen/tsconfig.json
  system-test/system.ts
Labels: size: m

#649 chore(deps): Bump `gaxios`
  package.json
  src/index.ts
Labels: size: s

#653 fix: remove the space from the log system string
  src/index.ts
Labels: size: xs
